### ISSUE TITLE
docker compose 安装后 管理界面报503

### ISSUE THREAD

**Issue by Dev-Wiki** [typecho/Dockerfile#10]
## 安装方式: docker compose
```yaml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4
    volumes:
      - /var/typecho:/app/usr 
    environment:
      TYPECHO_SITE_URL: https://blog.devwiki.net
    ports:
      - "2080:80"
```

## Docker安装过程结果
![image](https://user-images.githubusercontent.com/12946956/159112520-ad83a25c-a1e4-4daf-bd04-4ab2fa125ea5.png)

## typecho 安装过程

![image](https://user-images.githubusercontent.com/12946956/159112545-ed11ca7b-2b55-4dde-b1e5-00fd59d115b9.png)

![image](https://user-images.githubusercontent.com/12946956/159112610-45732a61-ab4e-45be-82bf-469959ecd88b.png)

修改db 路径后可安装:
![image](https://user-images.githubusercontent.com/12946956/159112619-1221e348-2ad0-4919-95b8-2b3d51bf77d3.png)

![image](https://user-images.githubusercontent.com/12946956/159112634-13975a5c-08c3-4163-8727-d38456136985.png)

![image](https://user-images.githubusercontent.com/12946956/159112652-2c562c98-efc5-4685-8c94-ab4c2ee93a9a.png)

![image](https://user-images.githubusercontent.com/12946956/159112663-6fbb2220-d660-4796-a4cd-286743216263.png)

![image](https://user-images.githubusercontent.com/12946956/159112696-b2dcc8a6-3474-44e1-822d-9f06723fa869.png)

![image](https://user-images.githubusercontent.com/12946956/159112702-d12f5d10-613d-4bf8-b79a-998907c93877.png)
