### ISSUE TITLE
TYPECHO_INSTALL设置为0, 却自动安装

### ISSUE THREAD

**Issue by Dev-Wiki** [typecho/Dockerfile#11]
安装脚本
```yml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4-apache
    volumes:
      - ./:/app/usr 
    environment:
      TIMEZONE: Asia/Shanghai
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 50m
      TYPECHO_INSTALL: 0
      TYPECHO_DB_ADAPTER: Pdo_SQLite
      TYPECHO_DB_FILE: 615a4d4dabd49.db
      TYPECHO_DB_PREFIX: db_
      TYPECHO_SITE_URL: https://blog.devwiki.net
      TYPECHO_USER_NAME: DevWiki
      TYPECHO_USER_MAIL: devwiki@qq.com
      TYPECHO_USER_PASSWORD: DevWiki
    ports:
      - "2080:80"
```

使用docker 安装后, 自动安装了.

![image](https://user-images.githubusercontent.com/12946956/159672765-fbbc7cf9-1b2e-4b8d-b1a7-acbadd5c6c63.png)
