### ISSUE TITLE
使用 https 访问安装界面错乱无法安装

### ISSUE THREAD

**Issue by Dev-Wiki** [typecho/Dockerfile#12]
docker配置:
```yml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4-apache
    volumes:
      - ./:/app/usr 
    environment:
      TIMEZONE: Asia/Shanghai
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 50m
    ports:
      - "80:80"
```

绑定了域名, 使用 https 访问界面如下:

![image](https://user-images.githubusercontent.com/12946956/159723202-086108c7-925f-48b7-b654-1fe4a7e646fe.png)

![Uploading image.png…]()

使用 http 访问正常
![image](https://user-images.githubusercontent.com/12946956/159723276-56c13fda-131f-4a21-a34c-9b4ce48cbbd4.png)

**Comment by Dev-Wiki** [comment]
查看了 install.php代码:
```php
    public function isSecure(): bool
    {
        return (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && !strcasecmp('https', $_SERVER['HTTP_X_FORWARDED_PROTO']))
            || (!empty($_SERVER['HTTP_X_FORWARDED_PORT']) && 443 == $_SERVER['HTTP_X_FORWARDED_PORT'])
            || (!empty($_SERVER['HTTPS']) && 'off' != strtolower($_SERVER['HTTPS']))
            || (!empty($_SERVER['SERVER_PORT']) && 443 == $_SERVER['SERVER_PORT'])
            || (defined('__TYPECHO_SECURE__') && __TYPECHO_SECURE__);
    }
```

应该是不符合上述条件, 我修改nginx转发如下:
```
plugin_host_header_rewrite = blog.devwiki.net
plugin_header_X-From-Where = frp
plugin_header_X_FORWARDED_PROTO= https
plugin_header_X_FORWARDED_PORT= 443
```
测试仍旧不行

**Comment by Dev-Wiki** [comment]
![image](https://user-images.githubusercontent.com/12946956/159730329-b1d89e74-c4dd-4c78-ae8b-3a025ee30eeb.png)

```php
<head>
    <meta charset="<?php _e('UTF-8'); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><?php _e('Typecho 安装程序'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php $options->adminStaticUrl('css', 'normalize.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php $options->adminStaticUrl('css', 'grid.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php $options->adminStaticUrl('css', 'style.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php $options->adminStaticUrl('css', 'install.css') ?>" />
    <script src="<?php $options->adminStaticUrl('js', 'jquery.js'); ?>"></script>
</head>
```
从代码看这里计算 adminStaticUrl 的 scheme 返回了 http 而非 https, 最后落到上面的函数那里, 我这里没环境无法调试

**Comment by joyqi** [comment]
这个应该属于https变量判断的问题，你可以放一个phpinfo文件看看这些变量是否传递过来了。

**Comment by Dev-Wiki** [comment]
> 这个应该属于https变量判断的问题，你可以放一个phpinfo文件看看这些变量是否传递过来了。

我本地docker测试也是不行, 配置如下:
```yml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4-apache
    volumes:
      - ./:/app/usr 
    environment:
      TIMEZONE: Asia/Shanghai
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 50m
      TYPECHO_SITE_URL: https://blog.devwiki.net
    ports:
      - "80:80"
      - "4443:443"
```

同时 host 修改为:
```
127.0.0.1 blog.devwiki.net
```

使用 http://blog.devwiki.net/install.php 能打开页面, 但是使用https 无法打开页面.
