### ISSUE TITLE
如果TYPECHO_INSTALL设置为1，容器每次重建都会重新安装吗

### ISSUE THREAD

**Issue by Sagit-chu** [typecho/Dockerfile#15]
如果`TYPECHO_INSTALL`设置为`“1”`，容器重建会自动安装吗
link：https://github.com/truecharts/apps/pull/2374#discussion_r840369883_

**Comment by joyqi** [comment]
会执行安装脚本，但是如果安装脚本判断已经安装完成，就不会再次安装

**Comment by Oaklight** [comment]
> 会执行安装脚本，但是如果安装脚本判断已经安装完成，就不会再次安装

判断条件是什么呢？我的docker安装完之后每次重启都会重新安装。
无论TYPECHO_INSTALL=1被注释掉还是保留。
现在是1.2.0版本

```yml
version: '3.7'

services:
  typecho:
    image: joyqi/typecho:nightly-php8.0-apache
    container_name: typecho-server
    restart: always
    environment:
      - TYPECHO_SITE_URL=https://blog.some.com
      - TIMEZONE=Asia/Shanghai
      # - TYPECHO_INSTALL=1 # 设置为1将运行自动安装脚本 
      - TYPECHO_DB_ADAPTER=Pdo_SQLite # 数据驱动器Pdo_Mysql, Pdo_SQLite, Pdo_Pgsql, Mysqli, SQLite, Pgsql.
      - TYPECHO_DB_FILE=/app/usr/typecho.sqlite.db
      - TYPECHO_DB_PREFIX=typecho_
    ports:
      - 9000:80
    volumes:
      - ~/typecho:/app/usr
```
