### ISSUE TITLE
安装1.2.0版本,管理界面一直提示版本.

### ISSUE THREAD

**Issue by Dev-Wiki** [typecho/Dockerfile#16]
![image](https://user-images.githubusercontent.com/12946956/161435166-cedfdaf5-3163-4104-bab4-8d6bbb48b71b.png)

使用版本为: joyqi/typecho:1.2.0-php7.4-apache

**Comment by Dev-Wiki** [comment]
本地docker测试也是
![image](https://user-images.githubusercontent.com/12946956/161435270-fb00eaa7-9980-459d-a164-1d4c64c9ab73.png)

使用方式 docker-compose

```yml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:1.2.0-php7.4-apache
    volumes:
      - ./:/app/usr 
    environment:
      TIMEZONE: Asia/Shanghai
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 50m
      TYPECHO_SITE_URL: http://blog.devwiki.net
    ports:
      - "80:80"
```
