### ISSUE TITLE
容器执行脚本init.sh里面设置usr/uploads疑问

### ISSUE THREAD

**Issue by flyisnow** [typecho/Dockerfile#25]
代码里写的是
```
check_and_make 'usr/uploads' '755'
```
第一次执行install.php时，会提示uploads无权限，改为766后，安装成功

**Comment by flyisnow** [comment]
我目前使用的容器镜像是`oyqi/typecho:nightly-php7.4-fpm-alpine`。
另外，这个方法
```
check_and_make() {
    if [ ! -e /app/$1 ]; then
        mkdir -p /app/$1
        chown -Rf www-data:www-data /app/$1
    fi

    if [ -n "$2" ]; then
        chmod $2 /app/$1
    fi
}
```
改为这样是不是更好，毕竟容器里执行，我修改了一次，下次就不用再修改了
```
check_and_make() {
    if [ ! -e /app/$1 ]; then
        mkdir -p /app/$1
        chown -Rf www-data:www-data /app/$1
       if [ -n "$2" ]; then
          chmod $2 /app/$1
       fi
    fi


}
```

**Comment by naoki66** [comment]
这个问题一直延续到nightly-php8.2-apache  我群晖多次安装不了，来搜索ssue才看到你的解决问题方法

**Comment by sy-records** [comment]
这个也没问题哇 怎么安装不了？命令发出来

`docker run --name typecho-server -d joyqi/typecho:nightly-php8.2-apache` 我可以安装啊

**Comment by naoki66** [comment]
> 这个也没问题哇 怎么安装不了？命令发出来
> 
> `docker run --name typecho-server -d joyqi/typecho:nightly-php8.2-apache` 我可以安装啊

`services:
  typecho:
    image: joyqi/typecho:nightly-php8.2-apache
    container_name: typecho-server
    restart: always
    environment:
      - 'TYPECHO_SITE_URL=https://XXXX.XXXX.XXX'
      - 'TIMEZONE=Asia/Shanghai'
      - 'MAX_POST_BODY=100M'
      - 'MEMORY_LIMIT=300M'
      - 'TYPECHO_USER_NAME=XXXX'
      - 'TYPECHO_USER_PASSWORD=XXXXXX'
      - 'TYPECHO_USER_MAIL=XXXXXX@qq.com'
      - 'TYPECHO_DB_ADAPTER=MySQL'
      - 'TYPECHO_DB_HOST=172.17.0.1'
      - 'TYPECHO_DB_PORT=1183'
      - 'TYPECHO_DB_USER=typecho'
      - 'TYPECHO_DB_PASSWORD=XXXXXX'
      - 'TYPECHO_DB_DATABASE=typecho'
      - 'TYPECHO_DB_CHARSET=utf8mb4'   
      - 'TYPECHO_INSTALL=0'      
    network_mode: "bridge"  
    ports:
      - 1182:80
    volumes:
      - /volume2/DockerConfig/typecho/typecho_data:/app/usr
    depends_on:
      - DB

  DB:
    container_name: typecho_mysql
    image: mysql:9.4
    network_mode: bridge
    ports:
      - 1183:3306
    environment:
      - 'TZ=Asia/Shanghai'
      - 'MYSQL_ROOT_PASSWORD=XXXXXXX'
      - 'MYSQL_USER=typecho'
      - 'MYSQL_PASSWORD=XXXXXXX'
      - 'MYSQL_DATABASE=typecho'
      - 'user=1026:100'
    volumes:
      - /volume2/DockerConfig/typecho/db_data:/var/lib/mysql
    restart: always   
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]  
      interval: 3s
      retries: 5
      start_period: 30s  `

**Comment by sy-records** [comment]
没问题，正常安装了，并且可以上传图片

```yml
services:
  typecho:
    image: joyqi/typecho:nightly-php8.2-apache
    container_name: typecho-server
    restart: always
    volumes:
      - ./typecho_data:/app/usr
    depends_on:
      - DB

  DB:
    container_name: typecho_mysql
    image: mysql:8.4
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=typecho
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=typecho
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
```
