### ISSUE TITLE
这么多镜像 Tag 不知道该用哪个

### ISSUE THREAD

**Issue by hueralin** [typecho/Dockerfile#36]

**Comment by hueralin** [comment]
纯小白，想用最简单的方式，快速部署一个博客

**Comment by joyqi** [comment]
我想你可以把你自己的需求详细描述一下，以及你现在所拥有的资源情况。

**Comment by hueralin** [comment]
好的，一台普通的云服务器，CentOS 7，1 核 2G，目前有 nginx 和 mysql （均非容器）在跑，不想自己配置环境，想用 docker run 直接起一个最新版本的 typecho，连上自己的 mysql，并使用 nginx 反向代理一下。谢谢~

**Comment by Dev-Wiki** [comment]
我目前使用的:
```yaml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:1.2.1-php7.4-apache
    volumes:
      - /share/Docker/blog_typecho/installer:/app 
      - /share/Docker/blog_typecho/:/app/usr
    environment:
      TIMEZONE: Asia/Shanghai
      TYPECHO_INSTALL: 0
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 51m
      TYPECHO_SITE_URL: https://blog.devwiki.net
    ports:
      - "2061:80"
```
