### ISSUE TITLE
docker安装完typecho，访问报502

### ISSUE THREAD

**Issue by Rum-cro** [typecho/Dockerfile#59]
```
version: "3.7"
services:
  typecho:
    image: joyqi/typecho:1.2.1-php7.4-fpm
    container_name: typecho-server
    restart: always
    environment:
      - TYPECHO_SITE_URL=https://your-domain.com
      - TYPECHO_DB_USER=user
      - TYPECHO_DB_PASSWORD=password
      - TYPECHO_DB_DATABASE=typecho
      - TYPECHO_DB_CHARSET=utf8mb4
      - TYPECHO_USER_NAME=user
      - TYPECHO_USER_PASSWORD=password
      - TYPECHO_USER_MAIL=admin@localhost.local
    ports:
      - 8080:80
    volumes:
      - /var/typecho:/app/usr
```

隐私部分我已隐藏，直接用`ip:8080`或用npm反代访问报`502`错误
