### ISSUE TITLE
docker compose 安装后 管理界面报503

### ISSUE THREAD

**Issue by Dev-Wiki** [typecho/Dockerfile#9]
## 安装方式: docker compose
```yaml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4
    volumes:
      - /var/typecho:/app/usr 
    environment:
      TYPECHO_SITE_URL: https://blog.devwiki.net
    ports:
      - "2080:80"
```

## Docker安装过程结果
![image](https://user-images.githubusercontent.com/12946956/159112520-ad83a25c-a1e4-4daf-bd04-4ab2fa125ea5.png)

## typecho 安装过程

![image](https://user-images.githubusercontent.com/12946956/159112545-ed11ca7b-2b55-4dde-b1e5-00fd59d115b9.png)

![image](https://user-images.githubusercontent.com/12946956/159112610-45732a61-ab4e-45be-82bf-469959ecd88b.png)

修改db 路径后可安装:
![image](https://user-images.githubusercontent.com/12946956/159112619-1221e348-2ad0-4919-95b8-2b3d51bf77d3.png)

![image](https://user-images.githubusercontent.com/12946956/159112634-13975a5c-08c3-4163-8727-d38456136985.png)

![image](https://user-images.githubusercontent.com/12946956/159112652-2c562c98-efc5-4685-8c94-ab4c2ee93a9a.png)

![image](https://user-images.githubusercontent.com/12946956/159112663-6fbb2220-d660-4796-a4cd-286743216263.png)

![image](https://user-images.githubusercontent.com/12946956/159112696-b2dcc8a6-3474-44e1-822d-9f06723fa869.png)

![image](https://user-images.githubusercontent.com/12946956/159112702-d12f5d10-613d-4bf8-b79a-998907c93877.png)

**Comment by Dev-Wiki** [comment]
改为自动安装同样的问题, 自动安装如下:
```yaml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4-apache
    volumes:
      - ./:/app/usr 
    environment:
      TIMEZONE: Asia/Shanghai
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 50m
      TYPECHO_INSTALL: 1
      TYPECHO_DB_ADAPTER: Pdo_SQLite
      TYPECHO_DB_FILE:615a4d4dabd49.db
      TYPECHO_DB_PREFIX: db_
      TYPECHO_SITE_URL: https://blog.devwiki.net
      TYPECHO_USER_NAME: name
      TYPECHO_USER_MAIL: email
      TYPECHO_USER_PASSWORD: password
    ports:
      - "2080:80"
```

自动安装后 前台页面可访问

![image](https://user-images.githubusercontent.com/12946956/159396238-304c9c24-f3ac-408f-921d-34e67a5c10f5.png)

管理界面 503

![image](https://user-images.githubusercontent.com/12946956/159396288-5e35aac7-f3bf-4ffa-95c0-7b47bd129609.png)

**Comment by Dev-Wiki** [comment]
> 改为自动安装同样的问题, 自动安装如下:
> 
> ```yaml
> version: '3'
> 
> services:    
>   typecho-server:
>     image: joyqi/typecho:nightly-php7.4-apache
>     volumes:
>       - ./:/app/usr 
>     environment:
>       TIMEZONE: Asia/Shanghai
>       MEMORY_LIMIT: 100m
>       MAX_POST_BODY: 50m
>       TYPECHO_INSTALL: 1
>       TYPECHO_DB_ADAPTER: Pdo_SQLite
>       TYPECHO_DB_FILE:615a4d4dabd49.db
>       TYPECHO_DB_PREFIX: db_
>       TYPECHO_SITE_URL: https://blog.devwiki.net
>       TYPECHO_USER_NAME: name
>       TYPECHO_USER_MAIL: email
>       TYPECHO_USER_PASSWORD: password
>     ports:
>       - "2080:80"
> ```
> 
> 自动安装后 前台页面可访问
> 
> ![image](https://user-images.githubusercontent.com/12946956/159396238-304c9c24-f3ac-408f-921d-34e67a5c10f5.png)
> 
> 管理界面 503
> 
> ![image](https://user-images.githubusercontent.com/12946956/159396288-5e35aac7-f3bf-4ffa-95c0-7b47bd129609.png)

找到原因了, 使用自动安装或者手动安装, 无法创建数据库文件, 会报503

如果手动拷贝原来的数据库文件, 所有者不同, 和已经关闭的一个 issue类似, 但是不知道为何会 创建的时候无法创建 db文件.

手动拷贝db 文件的目录如下:
![image](https://user-images.githubusercontent.com/12946956/159397375-08d68906-b87b-4784-8a4c-d4325d007951.png)

不复制的目录则不会有数据库文件:
![image](https://user-images.githubusercontent.com/12946956/159397444-0d973123-3727-4394-ba72-edbd1f9bc896.png)

**Comment by joyqi** [comment]
在 config.inc.php 文件里加上 `define('__TYPECHO_DEBUG__', true);`，然后看看报503时具体的报错信息是啥

**Comment by Dev-Wiki** [comment]
> 在 config.inc.php 文件里加上 `define('__TYPECHO_DEBUG__', true);`，然后看看报503时具体的报错信息是啥

不会生成此文件

**Comment by Dev-Wiki** [comment]
我重新安装控制台输出如下:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.52.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.52.2. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 22 13:11:50.190619 2022] [mpm_prefork:notice] [pid 27] AH00163: Apache/2.4.52 (Debian) PHP/7.4.28 configured -- resuming normal operations
[Tue Mar 22 13:11:50.190692 2022] [core:notice] [pid 27] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
172.29.52.1 - - [22/Mar/2022:13:13:27 +0800] "GET /install.php?step=2&driver=Pdo_SQLite HTTP/1.1" 302 271 "http://192.168.31.137:2080/install.php?step=2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
172.29.52.1 - - [22/Mar/2022:13:13:27 +0800] "GET / HTTP/1.1" 200 2209 "http://192.168.31.137:2080/install.php?step=2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
172.29.52.1 - - [22/Mar/2022:13:13:29 +0800] "GET /index.php/archives/1/ HTTP/1.1" 200 4053 "http://192.168.31.137:2080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
172.29.52.1 - - [22/Mar/2022:13:13:31 +0800] "GET /admin/login.php HTTP/1.1" 503 1289 "http://192.168.31.137:2080/index.php/archives/1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
```

**Comment by Dev-Wiki** [comment]
我修改了 数据库文件的 所属者 和组 同样不行

**Comment by Dev-Wiki** [comment]
> 在 config.inc.php 文件里加上 `define('__TYPECHO_DEBUG__', true);`，然后看看报503时具体的报错信息是啥

手动添加此文件和 内容, 页面没多余什么内容, 也没看到日志, 我使用的是威联通的nas的 docker环境, 你可试下:
[QuTScloud Online Demo | QNAP](https://www.qnap.com.cn/en/live-demo)

**Comment by joyqi** [comment]
我已经在本地复现了这个问题，是一个命令行安装时的数据目录问题，现在你可以临时把安装时的环境变量，然后再启动新的容器

```yml
TYPECHO_DB_FILE: 615a4d4dabd49.db
```

改成
```
TYPECHO_DB_FILE: /app/usr/615a4d4dabd49.db
```

后续我会在代码中修复

**Comment by Dev-Wiki** [comment]
> 

如果不自动安装, 安装过程界面选择db 的时候会:
![](https://user-images.githubusercontent.com/12946956/159112610-45732a61-ab4e-45be-82bf-469959ecd88b.png)

但是删除 前面的 `/app/usr` 能进行下一步, 但是后台仍旧503

**Comment by Dev-Wiki** [comment]
> 我已经在本地复现了这个问题，是一个命令行安装时的数据目录问题，现在你可以临时把安装时的环境变量，然后再启动新的容器
> 
> ```yaml
> TYPECHO_DB_FILE: 615a4d4dabd49.db
> ```
> 
> 改成
> 
> ```yaml
> TYPECHO_DB_FILE: /app/usr/615a4d4dabd49.db
> ```
> 
> 后续我会在代码中修复

按照这个修改 不会自动安装了, 会进入手动安装
![image](https://user-images.githubusercontent.com/12946956/159416475-04f52688-d617-4e34-a192-ce7e67583be0.png)

日志输出如下:
```
Typecho 1.2.0
PHP 7.4.28
安装程序检查到原有数据表已经存在.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.56.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.56.2. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 22 13:47:30.214003 2022] [core:warn] [pid 15] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Mar 22 13:47:30.223675 2022] [mpm_prefork:notice] [pid 15] AH00163: Apache/2.4.52 (Debian) PHP/7.4.28 configured -- resuming normal operations
[Tue Mar 22 13:47:30.223707 2022] [core:notice] [pid 15] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

**Comment by Dev-Wiki** [comment]
> 我已经在本地复现了这个问题，是一个命令行安装时的数据目录问题，现在你可以临时把安装时的环境变量，然后再启动新的容器
> 
> ```yaml
> TYPECHO_DB_FILE: 615a4d4dabd49.db
> ```
> 
> 改成
> 
> ```yaml
> TYPECHO_DB_FILE: /app/usr/615a4d4dabd49.db
> ```
> 
> 后续我会在代码中修复

按照此方式重新安装一个新的, 测试不会生成数据库文件

![image](https://user-images.githubusercontent.com/12946956/159417391-c9e8e260-9a1d-4faa-b65d-37e28c63d945.png)

**Comment by joyqi** [comment]
我在本地测试是可以的，你得把原来的容器和service都删掉

**Comment by Dev-Wiki** [comment]
> 我在本地测试是可以的，你得把原来的容器和service都删掉

我就担心有问题 所以重新创建的. 原来的都删除了, 目录都改了, 原来是的 typecho1, 新的是 devwikiblog

**Comment by Dev-Wiki** [comment]
> 我在本地测试是可以的，你得把原来的容器和service都删掉

在次重新安装, 仍旧不行, 控制台输出:
![image](https://user-images.githubusercontent.com/12946956/159423000-4ab92fd2-9ad1-4964-90af-d5cdb9421204.png)

安装的docker compose
![Snipaste_2022-03-22_14-40-02](https://user-images.githubusercontent.com/12946956/159423122-97884557-6cb6-480a-8c98-25558df87958.png)

需要手动创建 blog.db 文件么?

**Comment by Dev-Wiki** [comment]
> 我已经在本地复现了这个问题，是一个命令行安装时的数据目录问题，现在你可以临时把安装时的环境变量，然后再启动新的容器
> 
> ```yaml
> TYPECHO_DB_FILE: 615a4d4dabd49.db
> ```
> 
> 改成
> 
> ```yaml
> TYPECHO_DB_FILE: /app/usr/615a4d4dabd49.db
> ```
> 
> 后续我会在代码中修复

这样修改 仍旧会提示无法找到数据库

**Comment by joyqi** [comment]
我不知道是不是你的nas环境问题，在我本地测试了好几次都是可以正常创建的

```yml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:nightly-php7.4-apache
    volumes:
      - ./typecho:/app/usr 
    environment:
      TIMEZONE: Asia/Shanghai
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 50m
      TYPECHO_INSTALL: 1
      TYPECHO_DB_ADAPTER: Pdo_SQLite
      TYPECHO_DB_FILE: /app/usr/615a4d4dabd49.db
      TYPECHO_DB_PREFIX: db_
      TYPECHO_SITE_URL: https://blog.devwiki.net
      TYPECHO_USER_NAME: joyqi
      TYPECHO_USER_MAIL: magike.net@gmail.com
      TYPECHO_USER_PASSWORD: 123456
    ports:
      - "2080:80"
```

![截屏2022-03-22 下午6 00 17](https://user-images.githubusercontent.com/59437/159455471-342efdc7-e651-49a3-a6dc-26cbea05109e.png)
